// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using serverside.Data;

#nullable disable

namespace serverside.Migrations
{
    [DbContext(typeof(projectDbContext))]
    partial class projectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("serverside.Models.Domain.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 31, 20, 46, 22, 241, DateTimeKind.Utc).AddTicks(4202),
                            Email = "user5@example.com",
                            Password = "iyyG6pzy6k61F/0eBrdPOZ5/7A/vkuO0gqbPLisJICM=",
                            ReputationPoints = 6666,
                            Role = "Member",
                            Username = "UserFive"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 12, 31, 20, 46, 22, 241, DateTimeKind.Utc).AddTicks(4215),
                            Email = "user7@example.com",
                            Password = "WGCDbo8T/Jg3U5pZfUCGv8ApnlStkhSNVFOLXD/u+3w=",
                            ReputationPoints = 8888,
                            Role = "Admin",
                            Username = "UserSeven"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
